# Generated by Django 3.2.8 on 2022-03-23 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('milage', models.IntegerField(verbose_name='Пробег')),
                ('vin', models.CharField(max_length=14, verbose_name='VIN')),
                ('power', models.IntegerField(verbose_name='Лошадиные силы')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='Авто')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.carcolor', verbose_name='Цвет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Пользователь')),
            ],
        ),
    ]
