# Generated by Django 3.2.8 on 2022-03-27 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('rgb', models.CharField(max_length=7, verbose_name='Код')),
            ],
        ),
        migrations.AlterField(
            model_name='advert',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.carcolor', verbose_name='Цвет'),
        ),
    ]
