# Generated by Django 3.2.8 on 2022-03-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_carcolor'),
        ('advert', '0002_auto_20220327_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.carcolor', verbose_name='Цвет'),
        ),
        migrations.DeleteModel(
            name='CarColor',
        ),
    ]
