# Generated by Django 3.2.8 on 2022-03-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0003_auto_20220327_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='vin',
            field=models.CharField(max_length=17, verbose_name='VIN'),
        ),
    ]
