version: "3.9"

services:
  db:
    container_name: db
    image: postgres:12.9
    environment:
      POSTGRES_DB: "thatcar_db"
      POSTGRES_USER: "thatcar"
      POSTGRES_PASSWORD: "123456"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-network
  django-app:
    container_name: django-app
    build:
      context: .
      dockerfile: ./docker/Dockerfile_App
    networks:
      - app-network
    depends_on:
      - db
  proxy:
    image: nginx
    container_name: proxy
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./public/:/var/www/
    ports:
      - "1111:1111"
    networks:
      - app-network
    depends_on:
      - django-app

networks:
  app-network:
    driver: bridge
