# Generated by Django 3.2.8 on 2022-03-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=32, verbose_name='Ник')),
                ('firstName', models.CharField(max_length=32, verbose_name='Имя')),
                ('lastName', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('city', models.CharField(max_length=32, verbose_name='Город')),
            ],
        ),
    ]
