# Generated by Django 3.2.8 on 2022-03-23 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('rgb', models.CharField(max_length=7, verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=32, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.carbrand', verbose_name='Производитель')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.carcategory', verbose_name='Категория')),
            ],
        ),
    ]
