# Generated by Django 3.2.8 on 2022-03-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_auto_20220327_1357'),
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarColor',
        ),
    ]
